<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Changelog;

class ChangelogSeeder extends Seeder
{
    public function run(): void
    {
        // OLDEST TO NEWEST - agar yang terbaru punya ID tertinggi dan muncul paling atas
        $changelogs = [
            [
                'version' => 'v1.0.0',
                'release_date' => '2025-11-04',
                'title' => 'Initial Release - PGE System Foundation',
                'category' => 'feature',
                'is_major' => true,
                'changes' => [
                    'Project Setup: Laravel 11 dengan MySQL database (data_pge)',
                    'Modular System Architecture: Dynamic module assignment per user dengan config/modules.php',
                    'Role System: Admin & User roles dengan Spatie Laravel Permission',
                    'Database: Proper relationships, indexes, dan migrations untuk semua modul',
                    'UI Framework: Tailwind CSS & Alpine.js untuk modern interactive UI',
                    'Authentication: Login/logout system dengan role-based redirect',
                    'Module Registry: Centralized module configuration dengan assignable_to_user dan admin_only flags',
                ],
            ],
            [
                'version' => 'v1.1.0',
                'release_date' => '2025-11-04',
                'title' => 'Work Management Module - Core Features',
                'category' => 'feature',
                'is_major' => true,
                'changes' => [
                    'Work Plan Module: Create, read, update, delete work plans dengan project assignment',
                    'Work Realization Module: Track actual work completion dengan attachments support',
                    'Auto-numbering: RK-YYYYMMDD-XXXX untuk Work Plan, RL-YYYYMMDD-XXXX untuk Work Realization',
                    'WorkLocation Enum: Site, Office, WFH, WFA dengan label Indonesia',
                    'WorkField Enum: Administrasi, Elektrikal, Mekanikal, Sipil, HSE, Procurement, QC, PM',
                    'ApprovalStatus Enum: Pending, Approved, Rejected dengan type-safe helper methods',
                    'File Upload: Multiple file attachments untuk work realizations',
                    'Modal Forms: Alpine.js modal popups untuk create/edit dengan AJAX submission',
                    'Default Modules: Work Plan & Work Realization default tercentang untuk semua user baru',
                ],
            ],
            [
                'version' => 'v1.2.0',
                'release_date' => '2025-11-04',
                'title' => 'Leave Management Module - Separation & Approval',
                'category' => 'feature',
                'is_major' => true,
                'changes' => [
                    'Leave Submission Module: Cuti & Izin - pengajuan cuti dengan multiple leave types',
                    'Leave Approval Module: Daftar Cuti & Izin - approval workflow terpisah',
                    'Leave Types: Annual, Sick, Personal, Maternity, Paternity, Study Leave dengan auto-quota management',
                    'Auto-numbering: LV-YYYYMMDD-XXXX untuk leave requests',
                    'Leave Calculation: Automatic total days calculation dengan validation',
                    'PDF Generation: Leave certificate PDF untuk approved leaves',
                    'File Upload: Single file attachment untuk leave requests',
                    'Module Separation: Submission dan Approval menjadi 2 modul terpisah untuk granular access control',
                ],
            ],
            [
                'version' => 'v1.3.0',
                'release_date' => '2025-11-04',
                'title' => 'Payment Modules - SPD, Purchase, Vendor Payment',
                'category' => 'feature',
                'is_major' => true,
                'changes' => [
                    'SPD Module: Surat Perjalanan Dinas dengan dynamic cost table (add/remove items)',
                    'Purchase Module: Pembelian dengan item details (quantity, unit, price)',
                    'Vendor Payment Module: Pembayaran Vendor dengan invoice & PO tracking',
                    'Auto-numbering: SPD-YYYYMMDD-XXX, PC-YYYYMMDD-XXX, VP-YYYY-MM-XXXX',
                    'Module Separation: Setiap payment type menjadi modul terpisah (SPD, Pembelian, Pembayaran Vendor)',
                    'Payment Approval Module: Consolidated approval page untuk semua payment types',
                    'Dynamic Cost Tables: Add/remove cost items di SPD form dengan real-time total calculation',
                    'File Upload: Multiple file attachments untuk semua payment submissions',
                    'Project Integration: Semua payment modules terkait dengan projects',
                    'Vendor Management: Vendor selection untuk vendor payment dengan company info',
                ],
            ],
            [
                'version' => 'v1.4.0',
                'release_date' => '2025-11-04',
                'title' => 'User Management & Module Assignment System',
                'category' => 'feature',
                'is_major' => true,
                'changes' => [
                    'User Management: Full CRUD operations untuk users dengan role assignment',
                    'Module Assignment: Admin bisa assign/unassign modules ke individual users',
                    'Granular Access Control: Setiap user bisa punya set modules berbeda',
                    'Default Modules: Work Plan & Work Realization default tercentang untuk user baru',
                    'Module Sync: ModuleSeeder sync modules dari config/modules.php ke database',
                    'User-Module Relationship: Many-to-many relationship dengan pivot table',
                    'Visual Indicators: Default modules ditandai di UI untuk clarity',
                    'User Service: Centralized logic untuk user creation dan module assignment',
                ],
            ],
            [
                'version' => 'v1.5.0',
                'release_date' => '2025-11-04',
                'title' => 'Role-Based Routing System - /admin/* & /user/*',
                'category' => 'feature',
                'is_major' => true,
                'changes' => [
                    'Route Prefixing: Admin routes menggunakan /admin/* prefix, User routes menggunakan /user/* prefix',
                    'Dynamic Sidebar: Sidebar automatically convert user.* routes ke admin.* untuk admin users',
                    'Special Route Handling: Approval modules (leave-approval, payment-approval) menggunakan route khusus',
                    'Route Middleware: Role-based middleware protection untuk semua routes',
                    'Login Redirect: Admin redirect ke /admin/dashboard, User redirect ke /user/dashboard',
                    'Consistent Navigation: Semua modules accessible melalui prefix yang sesuai dengan role',
                    'Route Name Mapping: Admin routes menggunakan ->names() untuk proper route name generation',
                ],
            ],
            [
                'version' => 'v1.6.0',
                'release_date' => '2025-11-04',
                'title' => 'Modal Forms & UI Improvements',
                'category' => 'improvement',
                'is_major' => true,
                'changes' => [
                    'Wide Modal Layout: Modal forms menggunakan 3-column grid (md:grid-cols-3) untuk wide layout',
                    'No Scrolling: Modal forms tidak perlu scroll dengan optimized field arrangement',
                    'Alpine.js Integration: Proper Alpine.js data component registration dengan alpine:init event',
                    'Modal Width: sm:max-w-7xl untuk modal forms (lebih lebar dari default)',
                    'Compact Design: Reduced spacing, smaller text (text-sm) untuk lebih banyak content visible',
                    'Dynamic Form Fields: Cost tables, item lists dengan add/remove functionality',
                    'Real-time Calculations: Total cost, total price calculation dengan Alpine.js',
                    'Form Validation: Client-side dan server-side validation dengan error display',
                    'AJAX Submission: Form submission tanpa page reload dengan success/error handling',
                ],
            ],
            [
                'version' => 'v1.6.1',
                'release_date' => '2025-11-04',
                'title' => 'Payment Module Separation - Individual Pages',
                'category' => 'improvement',
                'is_major' => false,
                'changes' => [
                    'Module Split: Payment submission dipisah menjadi 3 modul terpisah (SPD, Pembelian, Pembayaran Vendor)',
                    'Individual Pages: Setiap payment type punya halaman index sendiri',
                    'Consolidated Approval: Payment approval tetap 1 halaman yang merangkup semua payment types',
                    'Route Updates: Routes untuk spd, purchases, vendor-payments di user dan admin groups',
                    'Sidebar Updates: 3 modul terpisah muncul di sidebar (SPD, Pembelian, Pembayaran Vendor)',
                    'Controller Updates: SpdController, PurchaseController, VendorPaymentController dengan proper redirects',
                    'Module Config: Updated config/modules.php untuk remove payment-submission dan add 3 modules baru',
                    'Database Sync: ModuleSeeder sync perubahan ke database modules table',
                ],
            ],
            [
                'version' => 'v1.6.2',
                'release_date' => '2025-11-04',
                'title' => 'Bug Fixes - Modal Popups & Alpine.js Scope',
                'category' => 'bugfix',
                'is_major' => false,
                'changes' => [
                    'Fixed: Modal popups tidak muncul karena Alpine.js scope issue',
                    'Fixed: showModal is not defined error - modal harus dalam scope x-data parent',
                    'Fixed: Alpine.js component registration dengan proper alpine:init event listener',
                    'Fixed: Script placement - Alpine data registration sebelum Alpine scans DOM',
                    'Fixed: Modal x-data duplicate - removed duplicate x-data dari modal component',
                    'Fixed: Alpine.js defer loading compatibility dengan inline script registration',
                    'Improved: Modal visibility dengan x-cloak dan style="display: none;" untuk prevent FOUC',
                    'Improved: Alpine.js component structure dengan proper scope inheritance',
                ],
            ],
            [
                'version' => 'v1.7.0',
                'release_date' => '2025-11-04',
                'title' => 'UI Standardization & Button Styling',
                'category' => 'improvement',
                'is_major' => false,
                'changes' => [
                    'Button Standardization: Semua buttons menggunakan bg-blue-600 hover:bg-blue-700 shadow-sm',
                    'Filter Tabs: Active bg-blue-600 text-white, Inactive bg-gray-100 text-gray-700 hover:bg-gray-200',
                    'Table Headers: Standardized bg-blue-600 untuk semua table headers',
                    'Empty States: Consistent empty state design dengan icon dan call-to-action buttons',
                    'Status Badges: Color-coded badges (yellow=pending, green=approved, red=rejected)',
                    'Form Inputs: Consistent styling dengan text-sm, rounded-lg, focus:ring-2 focus:ring-blue-500',
                    'Modal Headers: Consistent dark blue header dengan close button',
                    'Responsive Design: Mobile-friendly dengan proper breakpoints',
                ],
            ],
            [
                'version' => 'v1.8.0',
                'release_date' => '2025-11-04',
                'title' => 'Payment Approval & Rejection System',
                'category' => 'feature',
                'is_major' => true,
                'changes' => [
                    'Payment Approval Module: Consolidated approval page untuk SPD, Purchase, Vendor Payment',
                    'Approval Workflow: Approve/reject dengan reason/notes support',
                    'Rejection Modal: Modal popup untuk input rejection reason',
                    'Dynamic Route Generation: Approval routes menggunakan dynamic route prefix (no hardcoding)',
                    'Status Filtering: Filter by type (SPD, Purchase, Vendor Payment) dan status (Pending, Approved, Rejected)',
                    'Approval History: Track approval timestamp dan approver information',
                    'Real-time Updates: Status updates dengan AJAX untuk smooth UX',
                    'Security: Approval routes protected dengan proper middleware',
                ],
            ],
            [
                'version' => 'v1.9.0',
                'release_date' => '2025-11-04',
                'title' => 'Project Monitoring & Dashboard',
                'category' => 'feature',
                'is_major' => true,
                'changes' => [
                    'Project Monitoring: Centralized project tracking dengan role-based data access',
                    'Dashboard: Role-based dashboard dengan recent activity dan statistics',
                    'Project Integration: Semua modules (Work, Payment, Leave) terkait dengan projects',
                    'Project Management: CRUD operations untuk projects (Admin only)',
                    'Statistics Cards: Quick stats untuk pending approvals, recent submissions',
                    'Recent Activity: Timeline view untuk recent submissions dan approvals',
                    'Role-based Visibility: Admin melihat semua data, User hanya melihat data sendiri',
                ],
            ],
            [
                'version' => 'v1.10.0',
                'release_date' => '2025-11-04',
                'title' => 'Documentation & Logs System',
                'category' => 'feature',
                'is_major' => true,
                'changes' => [
                    'Documentation Module: Comprehensive system documentation dengan tabbed interface',
                    'Changelog System: Version tracking dengan database-backed changelog',
                    'Activity Logs: User activity tracking untuk monitoring dan audit',
                    'Documentation Tabs: Overview, Roles, Modules, Workflow, Technical, Database, Changelog',
                    'System Overview: Version info, tech stack, database stats, module descriptions',
                    'Workflow Documentation: Step-by-step workflows untuk semua major processes',
                    'Technical Documentation: Database schema, relationships, API endpoints',
                    'Changelog Display: Version history dengan categories (feature, bugfix, improvement, security)',
                ],
            ],
            [
                'version' => 'v1.11.0',
                'release_date' => '2025-11-05',
                'title' => 'Project Searchable Select & Access Management Enhancement',
                'category' => 'feature',
                'is_major' => true,
                'changes' => [
                    'Project Searchable Select: Mengganti dropdown project dengan searchable input untuk efisiensi',
                    'API Endpoint: GET /projects/search untuk partial search by name/code atau fetch by ID',
                    'Alpine.js Component: Reusable projectSearchableSelect component dengan debounce 300ms',
                    'Auto-fetch Project Info: Auto-load project info by ID untuk edit mode',
                    'Integration: Terintegrasi di Work Plans, Work Realizations, dan Payment modals (SPD, Purchase, Vendor Payment)',
                    'Project Manager Access Types: Sistem akses granular dengan 3 tipe (PM, Finance, Full Access)',
                    'Access Type Management: Admin dapat assign user dengan tipe akses spesifik saat assign project manager',
                    'PM Access: User dengan akses PM hanya bisa melihat Work Plans & Work Realizations untuk project yang dikelola',
                    'Finance Access: User dengan akses Finance hanya bisa melihat Payment modules (SPD, Purchase, Vendor Payment)',
                    'Full Access: User dengan akses Full bisa melihat semua data (Work & Payment) untuk project yang dikelola',
                    'Project Management UI: Kolom User ditambahkan di Project Management index untuk menampilkan semua user yang terhubung dengan badge access type',
                    'Payment Module Project Link: Semua payment modules (SPD, Purchase, Vendor Payment) sekarang required untuk project_id',
                    'Internal Kantor Project: Project baru "Internal Kantor" (PRJ-INTERNAL-001) untuk mencatat pembelian kantor',
                    'Performance: Debouncing, request cancellation, dan memory cleanup untuk optimal performance',
                    'Security: SQL injection prevention dengan input validation dan type casting',
                    'Error Handling: Proper error handling untuk API errors dan response validation',
                    'Bug Fixes: Fixed double binding issue, race condition, memory leaks, missing null checks, dan N+1 query problems',
                    'UI Improvements: Perbaikan warna biru konsisten di leave approval modals, perbaikan tombol hijau menjadi biru di work realization',
                    'Leave Module: Removed day limits display dari leave type dropdown, hanya menampilkan jenis cuti',
                    'Default Modules: Fixed work-plan dan work-realization modules untuk muncul sebagai default modules di sidebar',
                ],
            ],
        ];

        foreach ($changelogs as $changelog) {
            Changelog::updateOrCreate(
                ['version' => $changelog['version']],
                $changelog
            );
        }

        $this->command->info('✅ Changelogs seeded successfully!');
        $this->command->info('   - Total versions: ' . count($changelogs));
    }
}
